### PR TITLE
vue-cli compatibility

### PR DESCRIPTION
**Pull request by zigomir**
As mentioned in #22 ;)

### CODE REVIEW

**Comment by egoist** [comment]
I think we can use `meta.json` to provide more options, eg:
- user prefers using jsx
- customize project name in `package.json`

like this one https://github.com/vuejs-templates/webpack/blob/dist/meta.json

**Comment by zigomir** [comment]
so you know all about it :)) totally, I'll add meta.json, makes sense so you can install less packages if you don't need them.

**Comment by egoist** [comment]
@zigomir that's very appreciated 😄

**Comment by zigomir** [comment]
@egoist done

**Comment by egoist** [comment]
Thanks for your work, merged 🎉 

I also add some extra feature to it https://github.com/egoist/vuepack/commit/6abb6292111a97f7cb4f675a1d3da3cef7cd4562

**Comment by zigomir** [comment]
Thank you for vuepack! :)

**Pull request closed without merging**
