### PR TITLE
Update saofile.js and templates to the SAO v1 format

### PR DESCRIPTION
**Pull request by shanoaice**
Changes:
* Rename sao.js to saofile.js and updates it to the newest SAO v1 format
* Use EJS templating instead of Handlebars (seem like SAO v1 does not support any templates other than EJS)

@egoist When I test this with my latest SAO locally, there will always be an error while processing gitInit -- like this:
```
error TypeError: Cannot read property 'outDir' of undefined
    at gitInit (/home/andy/.config/yarn/global/node_modules/sao/lib/GeneratorContext.js:50:17)
    at GeneratorContext.completed (/d/vuepack/saofile.js:67:5)
    at SAO.runGenerator (/home/andy/.config/yarn/global/node_modules/sao/lib/index.js:128:30)
    at async SAO.run (/home/andy/.config/yarn/global/node_modules/sao/lib/index.js:101:5)
```

I don't know why, but everything else is fine.

### CODE REVIEW

**Comment by shanoaice** [comment]
There is a workaround about the problem -- bind the Generator instance manually will solve the problem -- shipping it to this branch soon.

**Comment by KsRyY** [comment]
There is a workaround about the problem -- bind the Generator instance manually will solve the problem -- shipping it to this branch soon.

**Comment by shanoaice** [comment]
Also, the Vue CLI init (v2 legacy method) tools uses handlebars which is incompatible with the EJS template, so I will remove meta.json and drop the deprecated Vue CLI init support.

**Comment by shanoaice** [comment]
@egoist

**Comment by shanoaice** [comment]
I also need to publish this to a new package -- `sao-vuepack` to adapt to the SAO v1 generator naming. I will add you as a collaborator on that package @egoist.

**Comment by shanoaice** [comment]
I decided to switch back to the Handlebars template and put back Vue CLI support. Everything will be released in `sao-vuepack@4.0.0-pre1`.

**Pull request merged**
